"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.
Docs: https://docs.djangoproject.com/en/5.2/
"""

from __future__ import annotations

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

# Load variables defined locally in .env (placed next to manage.py in core/.env)
load_dotenv(BASE_DIR / ".env")


def _env(key: str, default: str | None = None, *, required: bool = False) -> str | None:
    """Fetch environment variables with optional validation."""
    value = os.getenv(key, default)
    if required and value in {None, ""}:
        raise ImproperlyConfigured(f"Missing required environment variable: {key}")
    return value


# ---------------------------
# Core security & debug
# ---------------------------
SECRET_KEY = _env("DJANGO_SECRET_KEY", "django-insecure-change-me")
DEBUG = _env("DJANGO_DEBUG", "False").lower() in {"1", "true", "yes", "on"}

_allowed_hosts = _env("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]

# CSRF trusted origins: default to local dev if not provided
_default_csrf = ["http://127.0.0.1:8000", "http://localhost:8000"]
_csrf_from_env = _env("DJANGO_CSRF_TRUSTED_ORIGINS")
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in ( (_csrf_from_env or ",".join(_default_csrf)).split(",") )
    if o.strip()
]

# Sessions & cookies (stable names; secure flags configurable via env)
SESSION_COOKIE_NAME = _env("DJANGO_SESSION_COOKIE_NAME", "przypadek_sessionid")
CSRF_COOKIE_SECURE = _env("DJANGO_CSRF_COOKIE_SECURE", "False").lower() in {"1","true","yes","on"}
SESSION_COOKIE_SECURE = _env("DJANGO_SESSION_COOKIE_SECURE", "False").lower() in {"1","true","yes","on"}


# ---------------------------
# Third-party service keys
# ---------------------------
# Available in app code via: from django.conf import settings; settings.OPENAI_API_KEY
OPENAI_API_KEY = _env("OPENAI_API_KEY")  # may be None; app code should handle this


# ---------------------------
# Application definition
# ---------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "chat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# ---------------------------
# Database (SQLite for dev)
# ---------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ---------------------------
# Password validation
# ---------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ---------------------------
# Internationalization
# ---------------------------
LANGUAGE_CODE = "pl"
TIME_ZONE = "Europe/Warsaw"
USE_I18N = True
USE_TZ = True


# ---------------------------
# Static files
# ---------------------------
STATIC_URL = "static/"
# For dev: serve static assets (e.g., favicon) from core/static
STATICFILES_DIRS = [BASE_DIR / "static"]

# ---------------------------
# Misc
# ---------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"
