# Generated by Django 5.2.7 on 2025-10-22 12:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("content", models.TextField(blank=True, default="")),
                ("diagnostics_norm", models.TextField(blank=True, default="")),
                ("meds_norm", models.TextField(blank=True, default="")),
                ("reco_norm", models.TextField(blank=True, default="")),
                ("dispo_norm", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("diagnostics", "Diagnostyka"),
                            ("first_exam", "Rozpoznanie wstępne"),
                            ("meds", "Leczenie ostre"),
                            ("reco", "Zalecenia"),
                            ("dispo", "Skierowanie / Dispo"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Szablon instrukcji z placeholderami: {case_norm}, {user_answers}, {bot_answers}, {actual_msg}"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructions",
                        to="chat.case",
                    ),
                ),
            ],
            options={
                "ordering": ["-active", "-version", "-created_at"],
            },
        ),
    ]
