# Generated by Django 5.2.7 on 2025-10-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="prelim_dx_raw",
            field=models.TextField(blank=True, default=""),
        ),
    ]
